################################################################################
# Prerequisites
################################################################################

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

################################################################################
# Development
################################################################################

# IDE
brew "dbeaver-community"                        # IDE to work with databases

# Containers
brew "docker"                                   # Pack, ship and run any application as a lightweight container
brew "docker-compose"                           # Isolated development environments using Docker
brew "docker-machine"                           # Create Docker hosts locally and on cloud providers
brew "lazydocker"                               # The lazier way to manage everything docker